var theUrl="https://script.google.com/macros/s/AKfycbwg46p8shI9z5uGQV33n-DP-Mgblo2zgUb969NmeYbmAnThnA/exec",sender="loginfr",tempStorage="",mail_regex="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}",username_regex="^[a-z0-9_]{1}[a-z0-9_\\.]{2,20}[a-z0-9_]{1}$",username_regex_char="[a-z]+",password_regex=/^(?=.{5,64})/,msg_out="Sto controllando...;Indirizzo gia' associato ad un altro account;Nome utente non disponibile;Le password non corrispondono;Username o password errati;Seleziona...;Errore nella registrazione;Inserisci un indirizzo email valido;Il tuo username non puo' iniziare con un punto;Il tuo username non pu\u00f2 terminare con un punto;Il tuo username deve contenere almeno una lettera;Il tuo username non pu\u00f2 contenere lettere maiuscole;Il tuo username deve essere lungo almeno 4 caratteri;Il tuo username non puo' superare i 22 caratteri;Il tuo username non puo' contenere caratteri speciali;La password deve contenere almeno 5 caratteri".split(";"),
username=document.getElementById("username_r"),psw1=document.getElementById("password1"),psw2=document.getElementById("password2"),pswBkp,username_msg=document.getElementById("username-msg"),username_l=document.getElementById("username_l"),password_l=document.getElementById("password_l");
function register(){username.disabled=!0;psw1.disabled=!0;psw2.disabled=!0;document.getElementById("registrati-btn").innerHTML="ATTENDI...";var a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){var c=JSON.parse(atob(a.responseText));c.r?(saveStorage(c),window.parent.postMessage('{"name":"salvaLogin"}',"*")):document.getElementById("error").innerHTML=msg_out[6];username.disabled=!1;psw1.disabled=!1;psw2.disabled=!1;document.getElementById("registrati-btn").innerHTML=
"REGISTRATI"}};pswBkp=psw1.value;var b={h:"r",n:username.value,psw:psw1.value};a.open("POST",theUrl,!0);a.setRequestHeader("Content-Type","application/x-www-form-urlencoded");a.send(btoa(JSON.stringify(b)));return!1}
function userNameValid(){if(username.value.match(username_regex)&&username.value.match(username_regex_char)){var a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){var c=JSON.parse(atob(a.responseText));c.v?(username.className="nes-input is-success",username.setCustomValidity(""),username_msg.innerHTML=""):(username.className="nes-input is-error",username.setCustomValidity(" "),username_msg.className="nes-text is-error",username_msg.innerHTML=msg_out[2]);return c.v}username.className=
"nes-input is-warning";username.setCustomValidity(" ");username_msg.className="nes-text is-warning";username_msg.innerHTML=msg_out[0]};var b={h:"vu",n:username.value};a.open("POST",theUrl,!0);a.setRequestHeader("Content-Type","application/x-www-form-urlencoded");a.send(btoa(JSON.stringify(b)))}else username.className="nes-input is-error",username.setCustomValidity(" "),b=username.value.match("[^a-zA-Z0-9_\\.]")?msg_out[14]:username.value.match("^[\\.]")?msg_out[8]:username.value.match("[\\.]$")?msg_out[9]:
username.value.match("^.{23,}$")?msg_out[13]:username.value.match("^.{0,3}$")?msg_out[12]:username.value.match("[A-Z]+")?msg_out[11]:msg_out[10],username.value&&(username_msg.className="nes-text is-error",username_msg.innerHTML=b)}username.addEventListener("invalid",userNameValid);psw2.addEventListener("invalid",passwordValid);psw2.addEventListener("change",passwordValid);username.addEventListener("change",userNameValid);var psw1_msg=document.getElementById("psw1-msg"),psw2_msg=document.getElementById("psw2-msg");
psw1.addEventListener("invalid",passwordPattern);psw1.addEventListener("keyup",passwordPattern);function getStorage(){window.parent.postMessage('{"name":"getStorage"}',"*");return new Promise(function(a){function b(c){c=JSON.parse(c.data);"storage"==c.name&&(console.log("storage: "+c.value),window.removeEventListener("message",b),a(c.value))}window.addEventListener("message",b)})}
function saveStorage(a){getStorage().then(function(b){try{if(null!=b){var c=JSON.parse(atob(b));c.n=a.n;c.key=a.key;a.s>c.s&&(c.s=a.s)}else c={n:a.n,key:a.key,s:a.s};setStorage(btoa(JSON.stringify(c)))}catch(d){logout()}})}
function passwordPattern(){psw1.value.match(password_regex)?(psw1.className="nes-input is-success",psw1.setCustomValidity(""),psw1_msg.innerHTML=""):(psw1.className="nes-input is-error",psw1.setCustomValidity(" "),psw1_msg.className="nes-text is-error",psw1.value.length&&(psw1_msg.innerHTML=msg_out[15]));psw2.value&&passwordValid()}
function loginFieldsValid(){var a=document.getElementById("username_l"),b=document.getElementById("password_l");if(a.value){a.setCustomValidity("");var c=!0;a.className="nes-input"}else a.setCustomValidity(" "),c=!1,a.className="nes-input is-error",a.addEventListener("change",loginFieldsValid);b.value?(b.setCustomValidity(""),a=!0,b.className="nes-input"):(b.setCustomValidity(" "),a=!1,b.className="nes-input is-error",b.addEventListener("change",loginFieldsValid));return c&&a}
function passwordValid(){psw2.value?psw1.value!=psw2.value?(psw2.className="nes-input is-error",psw2.setCustomValidity(" "),psw2_msg.className="nes-text is-error",psw2_msg.innerHTML=msg_out[3]):(psw2.className="nes-input is-success",psw2.setCustomValidity(""),psw2_msg.innerHTML=""):psw2.className="nes-input is-error";return psw1.value==psw2.value}
function toLogin(){document.getElementById("registrati").style.display="none";document.getElementById("hogia").style.display="none";document.getElementById("login").style.display="block";document.getElementById("nhogia").style.display="block"}function toReg(){document.getElementById("registrati").style.display="block";document.getElementById("hogia").style.display="block";document.getElementById("login").style.display="none";document.getElementById("nhogia").style.display="none"}
function accedi(){if(!loginFieldsValid())return!1;var a=new XMLHttpRequest;username_l.disabled=!0;password_l.disabled=!0;document.getElementById("accedi-btn").innerHTML="ATTENDI...";document.getElementById("error_l").innerHTML="";document.getElementById("password_l").className="nes-input is-disabled";document.getElementById("username_l").className="nes-input is-disabled";a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){var c=JSON.parse(atob(a.responseText));c.r?(document.getElementById("password_l").className=
"nes-input",document.getElementById("username_l").className="nes-input",document.getElementById("error_l").innerHTML="",saveStorage(c),window.parent.postMessage('{"name":"salvaLogin"}',"*")):(document.getElementById("password_l").className="nes-input is-error",document.getElementById("username_l").className="nes-input is-error",document.getElementById("error_l").className="nes-text is-error",document.getElementById("error_l").innerHTML=msg_out[4]);username_l.disabled=!1;password_l.disabled=!1;document.getElementById("accedi-btn").innerHTML=
"ACCEDI"}};var b=document.getElementById("password_l").value;b={h:"l",n:document.getElementById("username_l").value,psw:b};a.open("POST",theUrl,!0);a.setRequestHeader("Content-Type","application/x-www-form-urlencoded");a.send(btoa(JSON.stringify(b)));return!1}function chiudiLogin(){window.parent.postMessage('{"name":"chiudiLogin"}',"*")}window.addEventListener("message",receiveMessage,!1);document.addEventListener("DOMContentLoaded",requestStorage);
function receiveMessage(a){a=JSON.parse(a.data);"load"==a.name&&requestStorage();"storage"==a.name&&(tempStorage=a.value,logged())}function requestStorage(){window.parent.postMessage(JSON.stringify({name:"getStorage"}),"*")}function setStorage(a){var b={name:"setStorage",value:a};tempStorage=a;window.parent.postMessage(JSON.stringify(b),"*")}
function logged(){document.getElementById("register-form").reset();document.getElementById("login-form").reset();try{var a=JSON.parse(atob(tempStorage))}catch(b){a={key:null}}a.key?(document.getElementById("login").style.display="none",document.getElementById("registrati").style.display="none",document.getElementById("logout").style.display="block",document.getElementById("nhogia").style.display="none",document.getElementById("hogia").style.display="none",document.getElementById("loggedUserName").innerHTML=
a.n):(document.getElementById("login").style.display="none",document.getElementById("registrati").style.display="block",document.getElementById("logout").style.display="none",document.getElementById("nhogia").style.display="none",document.getElementById("hogia").style.display="block")}document.getElementById("logout-btn").addEventListener("click",logout);
function logout(){tempStorage="";window.parent.postMessage('{"name":"clearStorage"}',"*");window.parent.postMessage('{"name":"salvaLogin"}',"*")}document.getElementById("username_r").addEventListener("input",forceLower);document.getElementById("username_l").addEventListener("input",forceLower);function forceLower(a){a.target.value=a.target.value.toLowerCase()};